language: node_js
node_js:
 — “8.9.4”
branches:
 only:
 — main
before_script:
 — npm install -g ionic
 — npm ci 
script:
 — ionic build
deploy:
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: main